# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
# WARNING: Using LWJGL2 is no longer recommend, and some methods in LWJGL2 will be unavailable.
# If you are porting an old mod lazily just set this to true.
enable_lwjglx = true

# Mod Information
# HIGHLY RECOMMEND complying with SemVer for mod_version: https://semver.org/
mod_version = 0.7.1
root_package = jp.s12kuma01
mod_id = celeritasextra
mod_name = Celeritas Extra

# Mod Metadata (Optional)
mod_description = An unofficial client-side add-on, built for Cleanroom. Adapted for Actinium (Actinium-compatible).
mod_url = https://github.com/Sumire-Labs/Celeritas-Extra
mod_update_json =
# Delimit authors with commas
mod_authors = Sumire Labs, s12kuma01, dspqle
mod_credits = FlashyReese, dima_dencep
mod_logo_path = assets/celeritasextra/icon.png
mod_issue_tracker = https://github.com/Sumire-Labs/Celeritas-Extra/issues

# Run Configurations
# If multiple arguments/tweak classes are stated, use spaces as the delimiter
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
# Good for debugging artifacts before uploading to remote maven
# GitHub actions won't run if this is true, test this by running the task `publishToMavenLocal`
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# If any properties changes below this line, refresh gradle again to ensure everything is working correctly.
# ----------------------------------------------------------------------------------------------------------------------

# Access Transformers
# A way to change visibility of Minecraft's classes, methods and fields.
# AT files should be in the root of src/main/resources with the filename formatted as: `mod_id_at.cfg`.
# Use `access_transformer_locations` in build.gradle for custom AT filenames or multiple space-delimited files.
# WARNING: Use MCP names in AT files. UniMined remaps them to SRG names when building.
use_access_transformer = false

# Coremods
# The most powerful way to change Java classes at runtime; only enable this when an IFMLLoadingPlugin is required.
# Set `coremod_includes_mod` to false if the CoreMod does not also contain an @Mod class.
# When enabling this, `coremod_plugin_class_name` must name an IFMLLoadingPlugin implementation.
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
# Convenient way to allow downloading of assets from official vanilla Minecraft servers, CurseForge, or any direct links
# Documentation: https://github.com/CleanroomMC/AssetMover
use_asset_mover = true
asset_mover_version = 2.5
